modLoader="javafml"
loaderVersion="[31,)"
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="elementalcraft"
version="${file.jarVersion}"
displayName="ElementalCraft"
description='''ElementalCraft is a magic mod based around the 4 elements: fire, water, earth and air.'''

[[dependencies.elementalcraft]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.15.2-6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.15.2-1.2,)"
    ordering="AFTER"
    side="BOTH"